\version "2.24.0"
\header {
  title = "Schoolhouse Trouble - Orquestra de Boutique"
    composer = "Minimalismo do Pânico"
    }

    \score {
      <<
          % ============ VIOLONCELO ============
              % O MIDI #42 é o som de Cello
                  \new Staff \with {
                        instrumentName = #"Violoncelo"
                              shortInstrumentName = #"Vc"
                                    midiInstrument = #"cello"
                                        } \relative c {
                                              \clef bass
                                                    \key c \minor
                                                          \time 4/4
                                                                \tempo "Agitato" 4 = 140
                                                                      
                                                                            c8\mf c16 c c8 c c4 c8 d
                                                                                  ees8 ees16 ees ees8 ees ees4 r4
                                                                                        d8 d16 d d8 d d4 d8 ees
                                                                                              f8 f16 f f8 f f4 r4
                                                                                                    
                                                                                                          c8 c16 c c8 c c4 c8 d
                                                                                                                aes8 aes16 aes aes8 aes aes4 r4
                                                                                                                      g8 g16 g g8 g g4 r4
                                                                                                                            ees8 ees16 ees ees8 ees ees4 r4
                                                                                                                                  
                                                                                                                                        c'8\f c16 c c8 c c4 c8 d
                                                                                                                                              ees8 ees16 ees ees8 ees ees4 r4
                                                                                                                                                    f8 f16 f f8 f f4 f8 ees
                                                                                                                                                          d8 d16 d d8 d d4 r4
                                                                                                                                                                
                                                                                                                                                                      c8 c16 c c8 c c4 r4
                                                                                                                                                                            g8 g16 g g8 g g4 r4
                                                                                                                                                                                  ees8 ees16 ees ees8 ees ees4 r4
                                                                                                                                                                                        c1\fermata \bar "|."
                                                                                                                                                                                            }
                                                                                                                                                                                                
                                                                                                                                                                                                    % ============ TRIÂNGULO ============
                                                                                                                                                                                                        % O MIDI #81 é o som de Triângulo (Triangle)
                                                                                                                                                                                                            \new Staff \with {
                                                                                                                                                                                                                  instrumentName = #"Triângulo"
                                                                                                                                                                                                                        shortInstrumentName = #"Trgl"
                                                                                                                                                                                                                              midiInstrument = #"triangle"
                                                                                                                                                                                                                                  } \relative c'' {
                                                                                                                                                                                                                                        \clef percussion
                                                                                                                                                                                                                                              \time 4/4
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                          c4\p r c r
                                                                                                                                                                                                                                                                c4 r c r
                                                                                                                                                                                                                                                                      c4 r c r
                                                                                                                                                                                                                                                                            c4 r c r
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                        c4 r c r
                                                                                                                                                                                                                                                                                              c4 r c r
                                                                                                                                                                                                                                                                                                    c4 r c r
                                                                                                                                                                                                                                                                                                          c4 r c r
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                      c8\mf c8 c8 c8 c4 c
                                                                                                                                                                                                                                                                                                                            c8 c8 c8 c8 c4 r4
                                                                                                                                                                                                                                                                                                                                  c8 c8 c8 c8 c4 c
                                                                                                                                                                                                                                                                                                                                        c8 c8 c8 c8 c4 r4
                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                    c4\f r c r
                                                                                                                                                                                                                                                                                                                                                          c4 r c r
                                                                                                                                                                                                                                                                                                                                                                c4 r c r
                                                                                                                                                                                                                                                                                                                                                                      c1\fermata \bar "|."
                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                  % ============ PRATO ============
                                                                                                                                                                                                                                                                                                                                                                                      % O MIDI #50 é o som de Prato de Ataque (Crash Cymbal)
                                                                                                                                                                                                                                                                                                                                                                                          \new Staff \with {
                                                                                                                                                                                                                                                                                                                                                                                                instrumentName = #"Prato"
                                                                                                                                                                                                                                                                                                                                                                                                      shortInstrumentName = #"Prt"
                                                                                                                                                                                                                                                                                                                                                                                                            midiInstrument = #"crash cymbal"
                                                                                                                                                                                                                                                                                                                                                                                                                } \relative c' {
                                                                                                                                                                                                                                                                                                                                                                                                                      \clef percussion
                                                                                                                                                                                                                                                                                                                                                                                                                            \time 4/4
                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                        r1 r1 r1 r1
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                    c1\ff
                                                                                                                                                                                                                                                                                                                                                                                                                                                          r1 r1 r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      c1\ff
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  c1\ff
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c1\fff\fermata
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          r1 r1 r1 \bar "|."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      % ============ SLAPAPHONE ============
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          % O MIDI #37 é o Slap Bass. O Slapaphone tem exatamente o timbre "boing" seco.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \new Staff \with {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    instrumentName = #"Slapaphone"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          shortInstrumentName = #"Slp"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                midiInstrument = #"slap bass 1"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    } \relative c' {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \clef treble
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                \time 4/4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            r1 r1 r1 r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  r1 r1 r1 r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              c4\mp r r2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          d4\mp r r2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c4\mf r r2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        r1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              c1\p\fermata \bar "|."
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        \layout { }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          \midi { }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }